version: "3"
services:
  public:
    image: node:lts-alpine
    network_mode: host
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: "npm run start:docker"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_KEY
      - AWS_DEFAULT_REGION
      - AWS_ROUTE53_HOSTED_ZONE_ID
      - AWS_ROUTE53_RECORD_NAME
      - AWS_CHECK_IP_ENDPOINT=https://checkip.amazonaws.com
  private:
    network_mode: host
    image: node:lts-alpine
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: "npm run start:docker"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_KEY
      - AWS_DEFAULT_REGION
      - AWS_ROUTE53_HOSTED_ZONE_ID=SETME
      - AWS_ROUTE53_RECORD_NAME
      - AWS_CHECK_IP_ENDPOINT=http://169.254.169.254/latest/meta-data/local-ipv4
